# Generated by Django 5.0.4 on 2024-04-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_note', '0003_alter_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
