# Generated by Django 5.0.4 on 2024-04-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_note', '0004_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
