# Generated by Django 5.0.3 on 2024-03-29 02:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('course_subject', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'core_course',
            },
        ),
    ]
