# Generated by Django 5.0.2 on 2024-02-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subjects',
            new_name='course_subject',
        ),
    ]
