# Generated by Django 5.0.2 on 2024-03-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_course', '0002_course_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
