# Generated by Django 5.0.2 on 2024-03-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_course', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='core_course',
        ),
    ]
