# Generated by Django 5.0.2 on 2024-03-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_course', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sections',
        ),
    ]
