# Generated by Django 5.0.2 on 2024-03-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_course', '0003_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
