# Generated by Django 5.0.2 on 2024-03-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_course', '0004_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
    ]
