# Generated by Django 5.0.2 on 2024-03-28 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_course', '0005_remove_course_name'),
        ('core_subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_subject', 'code'), name='unique_course_code'),
        ),
    ]
