# Generated by Django 5.0.2 on 2024-03-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
