# Generated by Django 5.0.2 on 2024-03-21 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicechatroom',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='voicechatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
