# Generated by Django 5.0.2 on 2024-03-21 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_voicechatroom_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voicechatroom',
            old_name='user',
            new_name='creator',
        ),
    ]
