# Generated by Django 5.0.2 on 2024-04-08 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_voice_chat', '0002_voicechatroom_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voicechatroom',
            name='banned_users',
            field=models.ManyToManyField(related_name='banned_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
