# Generated by Django 5.0.2 on 2024-04-10 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_voice_chat', '0003_voicechatroom_banned_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voicechatroom',
            name='accepted_users',
            field=models.ManyToManyField(blank=True, related_name='accepted_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voicechatroom',
            name='waiting_users',
            field=models.ManyToManyField(blank=True, related_name='waiting_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
