# Generated by Django 5.0.2 on 2024-03-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='core.posts',
        ),
    ]
