# Generated by Django 5.0.2 on 2024-03-27 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0002_badcontent_post_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badcontent',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_posts.post'),
        ),
    ]
