# Generated by Django 5.0.4 on 2024-04-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
