# Generated by Django 5.0.2 on 2024-03-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badcontent',
            name='reportedContent',
            field=models.TextField(default=''),
        ),
    ]
