# Generated by Django 5.0.3 on 2024-03-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0002_badcontent_post_reports'),
        ('core_posts', '0002_initial'),
    ]

    operations = [
    ]
