# Generated by Django 5.0.2 on 2024-04-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0003_reply_replyrating_reply_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='instructor_reply',
            field=models.BooleanField(default=False),
        ),
    ]
