# Generated by Django 5.0.2 on 2024-03-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0001_initial'),
        ('core_section', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='unique_module'),
        ),
    ]
