# Generated by Django 5.0.2 on 2024-03-20 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0001_initial'),
        ('core_section', '0002_alter_section_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core_section.section'),
        ),
    ]
