# Generated by Django 5.0.4 on 2024-04-19 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0002_module_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='course',
            new_name='course_id',
        ),
    ]
