# Generated by Django 5.0.4 on 2024-04-19 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_course', '0002_initial'),
        ('core_module', '0003_rename_course_module_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='core_course.course'),
        ),
    ]
