# Generated by Django 5.0.2 on 2024-03-29 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0002_module_unique_module'),
        ('core_quiz2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz2',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core_module.module'),
            preserve_default=False,
        ),
    ]
