# Generated by Django 5.0.3 on 2024-03-27 01:45


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_quiz2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz2',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionList', to='core_quiz2.quiz2'),
        ),
        migrations.AddField(
            model_name='quizrating',
            name='quiz2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_quiz2.quiz2'),
        ),
        migrations.AddField(
            model_name='quizrating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz2',
            name='ratings',
            field=models.ManyToManyField(related_name='rated_quizzes', through='core_quiz2.QuizRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='quizrating',
            unique_together={('user', 'quiz2')},
        ),
    ]
