# Generated by Django 5.0.2 on 2024-02-28 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_quiz2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='quiz2',
            name='body',
        ),
        migrations.RemoveField(
            model_name='quiz2',
            name='edited',
        ),
        migrations.AddField(
            model_name='quiz2',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='quiz2',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quiz2',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('answerList', models.ManyToManyField(related_name='answerList', to='core_quiz2.answer')),
                ('quiz2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_quiz2.quiz2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_quiz2.question'),
        ),
        migrations.AddField(
            model_name='quiz2',
            name='questionList',
            field=models.ManyToManyField(related_name='questionList', to='core_quiz2.question'),
        ),
    ]
