# Generated by Django 5.0.2 on 2024-03-01 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_course', '0004_remove_course_joined_users'),
        ('core_quiz2', '0002_answer_remove_quiz2_body_remove_quiz2_edited_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answerList',
        ),
        migrations.RemoveField(
            model_name='quiz2',
            name='questionList',
        ),
        migrations.AddField(
            model_name='quiz2',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_course.course'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerList', to='core_quiz2.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionList', to='core_quiz2.quiz2'),
        ),
        migrations.AlterField(
            model_name='quiz2',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
