# Generated by Django 5.0.2 on 2024-03-28 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_quiz2', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('quiz2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_quiz2.quiz2')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quiz2')},
            },
        ),
        migrations.AddField(
            model_name='quiz2',
            name='ratings',
            field=models.ManyToManyField(related_name='rated_quizzes', through='core_quiz2.QuizRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
