# Generated by Django 5.0.3 on 2024-04-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blacklisted_from_study_sessions',
            field=models.BooleanField(default=False),
        ),
    ]
