# Generated by Django 5.0.2 on 2024-03-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_course', '0002_course_creator'),
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='core_course.course'),
        ),
    ]
