# Generated by Django 5.0.2 on 2024-03-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.AddField(
            model_name='user',
            name='user_rating',
            field=models.IntegerField(default=0),
        ),
    ]
