# Generated by Django 5.0.2 on 2024-02-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_course', '0002_rename_subjects_course_course_subject'),
        ('core_user', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='core_course.course'),
        ),
    ]
