# Generated by Django 5.0.2 on 2024-03-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_course', '0001_initial'),
        ('core_user', '0003_remove_user_rating_user_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='core_course.course'),
        ),
    ]
