# Generated by Django 5.0.2 on 2024-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
